### ISSUE TITLE
error: package directory 'geeaddon' does not exist when pip install .

### ISSUE THREAD

**Issue by suredream** [samapriya/gee_asset_manager_addon#1]
Obtaining file:///Users/jxiong1/Dropbox/projects/gee_asset_manager
    Complete output from command python setup.py egg_info:
    running egg_info
    creating geeadd.egg-info
    writing geeadd.egg-info/PKG-INFO
    writing top-level names to geeadd.egg-info/top_level.txt
    writing dependency_links to geeadd.egg-info/dependency_links.txt
    writing entry points to geeadd.egg-info/entry_points.txt
    writing manifest file 'geeadd.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'geeaddon' does not exist

**Comment by samapriya** [comment]
Has been fixed now updated to v0.1.8. Install should work properly and includes dependencies in the setup.py file
