### ISSUE TITLE
Adding geeadd to conda-forge

### ISSUE THREAD

**Issue by giswqs** [samapriya/gee_asset_manager_addon#10]
I plan to incorporate geeadd into the [geemap](https://github.com/giswqs/geemap) package, making geeadd one of the dependencies. It would be nice to have this package available on [conda-forge](https://conda-forge.org/feedstocks/). Here is the [instruction](https://github.com/conda-forge/staged-recipes#getting-started) for adding a package to conda-forge. You can create a `meta.yaml` using `conda skeleton pypi geeadd`. Then fork [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes) and add a geeadd folder with the meta.yaml and LICENSE to the [recipes](https://github.com/conda-forge/staged-recipes/tree/master/recipes) folder. Submit a pull request and wait for the review and approval. I can help in this regard if needed. Thanks.

**Comment by samapriya** [comment]
Hi @giswqs 
I forked the repo and created the yaml file, would you mind checking and letting me know what else I am missing. I created the ```meta.yaml``` using ```conda skeleton pypi geeadd``` as suggested. I zipped the file because github doesn't allow for yaml attachment.


[meta.zip](https://github.com/samapriya/gee_asset_manager_addon/files/4533025/meta.zip)

Added the [yaml file here ](https://github.com/samapriya/staged-recipes/tree/master/recipes). Let me know and I can submit a pull request based on any other edits as needed.

**Comment by giswqs** [comment]
Your `meta.yaml` seems to be a bit different from what I generated from using `conda skeleton pypi geeadd`. See this [meta.yaml](https://gist.github.com/giswqs/08dac5935f5c94a6f1fc7cdd3f8d6bd0).

Following conda-forge's guidelines, a few edits are needed:

1. Added  `noarch: python` to `build`
2. For this `host`, you only need pip and python. All dependencies are placed within `run`
3. You will need to put the LICENSE file within your recipe folder. Check out my [geemap-feedstock](https://github.com/conda-forge/geemap-feedstock/tree/master/recipe) on conda-forge. You can also check my previous [pull-request](https://github.com/conda-forge/staged-recipes/pull/11094).

**Comment by samapriya** [comment]
Thanks @giswqs 
Do I need to specify that it is only compatible with python3 somewhere in the yaml file? Would you mind checking again here if the yaml file and license file placements is correct?

https://github.com/samapriya/staged-recipes/tree/master/recipes/geeadd

**Comment by giswqs** [comment]
It looks good to me. I believe you don't need to specify Python version in meta.yaml. Python versions are already specified in the setup.py of the package, which meta.ymal will inherit from.

**Comment by samapriya** [comment]
build seems to work in osx and windows but is failing during merge check for Linux. Would you mind taking a look?
https://github.com/conda-forge/staged-recipes/pull/11374

**Comment by samapriya** [comment]
Hey @giswqs 
Got it to work the yaml needed git to be available in the system.

**Comment by giswqs** [comment]
Great work! Just wait for the conda-forge team to review it.

**Comment by giswqs** [comment]
It seems [GitPython](https://gitpython.readthedocs.io/en/stable/intro.html#requirements) requires Git to be installed on the computer. This would be a barrier for users without Git on their computer. I would  suggest replacing it with the built-in library `urllib` if you are only downloading files from GitHub. See my examples [here](https://github.com/giswqs/geemap/blob/master/geemap/conversion.py#L906) and [here](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L2058).

**Comment by giswqs** [comment]
You can replace [Lines 213-216](https://github.com/samapriya/gee_asset_manager_addon/blob/master/geeadd/geeadd.py#L213) with urllib. See my sample functions below.

```
    Repo.clone_from(
        "https://github.com/samapriya/Earth-Engine-Datasets-List.git",
        os.path.join(lpath, folder_name),
    )
```

```
def download_from_url(url, out_file_name=None, out_dir='.', unzip=True):
    """Download a file from a URL (e.g., https://github.com/giswqs/whitebox/raw/master/examples/testdata.zip)
    Args:
        url (str): The HTTP URL to download.
        out_file_name (str, optional): The output file name to use. Defaults to None.
        out_dir (str, optional): The output directory to use. Defaults to '.'.
        unzip (bool, optional): Whether to unzip the downloaded file if it is a zip file. Defaults to True.
    """
    in_file_name = os.path.basename(url)

    if out_file_name is None:
        out_file_name = in_file_name
    out_file_path = os.path.join(os.path.abspath(out_dir), out_file_name)

    print('Downloading {} ...'.format(url))

    try:
        urllib.request.urlretrieve(url, out_file_path)
    except:
        print("The URL is invalid. Please double check the URL.")
        return

    final_path = out_file_path

    if unzip:
        # if it is a zip file
        if '.zip' in out_file_name:
            print("Unzipping {} ...".format(out_file_name))
            with zipfile.ZipFile(out_file_path, "r") as zip_ref:
                zip_ref.extractall(out_dir)
            final_path = os.path.join(os.path.abspath(
                out_dir), out_file_name.replace('.zip', ''))

        # if it is a tar file
        if '.tar' in out_file_name:
            print("Unzipping {} ...".format(out_file_name))
            with tarfile.open(out_file_path, "r") as tar_ref:
                tar_ref.extractall(out_dir)
            final_path = os.path.join(os.path.abspath(
                out_dir), out_file_name.replace('.tart', ''))

    print('Data downloaded to: {}'.format(final_path))

def clone_repo(out_dir='.', unzip=True):
    """Clones the geemap GitHub repository.
    Args:
        out_dir (str, optional): Output folder for the repo. Defaults to '.'.
        unzip (bool, optional): Whether to unzip the repository. Defaults to True.
    """
    url = 'https://github.com/giswqs/geemap/archive/master.zip'
    filename = 'geemap-master.zip'
    download_from_url(url, out_file_name=filename,
                      out_dir=out_dir, unzip=unzip)
```

**Comment by samapriya** [comment]
Used urllib method and modified a few lines to get the desired effect. All checks completed for the new version 0.4.4 and conda-forge yaml file was updated to remove git and updated to v0.4.4. This is also better since it reduces dependency on the project. Thanks for the suggestions, closing this for now.

**Comment by giswqs** [comment]
Excellent! Thank you for your prompt action!
