### ISSUE TITLE
Deprecated GEE functions 

### ISSUE THREAD

**Issue by giswqs** [samapriya/gee_asset_manager_addon#11]
Some functions being used in this package have been depreciated by GEE, such as `ee.data.cancelTask()`, `ee.data.getInfo()`, `ee.data.getList()`, `ee.data.getTaskList()`, `ee.data.getTaskStatus()`, `ee.data.setAssetProperties()`. You might want to consider updating these functions. 

![](https://i.imgur.com/7Wd3kKg.png)

**Comment by samapriya** [comment]
Thanks @giswqs 
Feel free to create a pull request and I will be happy to merge them. :)

**Comment by samapriya** [comment]
Wondering if we should open an issue with the Earth Engine command-line tool
https://github.com/google/earthengine-api/blob/5909d9a19a9b829d49b69f38ac4205b4924b21c9/python/ee/cli/commands.py#L842

**Comment by samapriya** [comment]
Finally made the changes and updates thanks for the feedback @giswqs . Expecting changes to asset properties tool so keeping that constant for now and will change in the future. Closing issue for now but feel free to comment or reopen
