### ISSUE TITLE
geeadd move errror

### ISSUE THREAD

**Issue by kongdd** [samapriya/gee_asset_manager_addon#12]
```bash
geeadd move --initial "projects/pml_evapotranspiration/landcover_impact/MCD12Q1_06" --final "projects/pml_evapotranspiration/landcover_impact/MCD12Q1_06_error"
# Collection does not exist: Creating projects/pml_evapotranspiration/landcover_impact/MCD12Q1_06_error#
# Parameter "parent" value "projects/pml_evapotranspiration/landcover_impact/MCD12Q1_06_error" does not match the pattern # "^projects/[^/]+/assets/.*$"
# Initial path projects/earthengine-legacy/assets/projects/pml_evapotranspiration/landcover_impact/MCD12Q1_06 not found
```

**Comment by samapriya** [comment]
HI @kongdd 
Just released v0.5.5 try that and let me know if that resolves your issue for now I have no way to test your assets without having access

**Comment by kongdd** [comment]
Thank you! I will have a try today or tomorrow

**Comment by kongdd** [comment]
Amazing! Works now.
All images moved successfully. But leave an empty ee.ImageCollection in the original path.

**Comment by samapriya** [comment]
Yes that is by design incase the process gets stuck or anything major. Feel free to Star the github repository, helps me build further and keeps me excited about working with the community

**Comment by kongdd** [comment]
Thanks for your amazing work. I have stared and forked this repository several years ago. 
Again, thanks for your quick response and action.
