### ISSUE TITLE
Incorrect credentials issue when uploading files to GEE Assets.

### ISSUE THREAD

**Issue by ZunyiXie** [samapriya/gee_asset_manager_addon#3]
Hi Sam,

Thanks very much for this tool. Everything seemed to work well for me except that I couldn’t upload a directory to GEE Assets due to the issue below after I typed the password. I am pretty sure I input the correct password and tried many times but always got the same error. Any suggestions? Thanks!

“2017–11–02 18:08:31,628 :: root :: ERROR :: Incorrect credentials. Probably. If you are sure the credentials are OK, ref
resh the authentication token. If it did not work report a problem. They might have changed something in the Matrix.”

Cheers

**Comment by samapriya** [comment]
Can you give me some details ( I tested the tool today and it seems to be working I have a windows OS and python 2.7.14) though I doubt that causes much of an issue.

- Operating system: A lot of people who are using mac when they ask for password first you have to enter the system password and then enter the gmail credentials. 
- Python version

**Comment by ZunyiXie** [comment]
Thanks, Sam.

I am on Windows 10 Education version and using my Uni computer, I have admin right to install software though.

I am using Anaconda Python 2.7.13.

I tried the pwd of my computer "space" my gmail pwd together just now, same error, and it won't give me chance to input pwd twice. 

I also found that if I use Git Bash, the upload function will stall, it is ok on PowerShell but has incorrect credentials issue, I am stuck :(.

Thanks!

Joey

**Comment by ZunyiXie** [comment]
Hi Sam,

I saw the link below on Google group, and the guy met the same issue of Incorrect credentials. He switched to cloud storage bucket which I am not familiar with, but I assume I could do the same to batch upload files?

https://groups.google.com/forum/#!searchin/google-earth-engine-developers/cloud$20storage$20bucket$20batch$20upload$20files%7Csort:date/google-earth-engine-developers/DyS_gHfZFr0/XHYSGBehAAAJ

Thanks!

Joey

**Comment by samapriya** [comment]
Hi Joey,
Do you have two factor authentication on your gmail? Also allow less secure apps
https://support.google.com/accounts/answer/6010255?hl=en

Because I know some people had this issue. You can also email me and then we can talk and you can show me the error if that persists. 

Sam

**Comment by ZunyiXie** [comment]
Hi Sam,

Thanks for your prompt reply. I did earthengine authenticate several times but it didn't have any effect.

I am going to check the link you provided and keep you updated.

Can I find your email here on GitHub? I am new to GEE but will be substantially involved in GEE world for my postdoc project, would like to keep in touch and study from you.

Thanks again for your help

Cheers

Joey

**Comment by samapriya** [comment]
Hi Joey,
earthengine authenticate does not use your password yes you can email samapriya.roy@gmail.com

Sam

**Comment by ZunyiXie** [comment]
Thanks a lot, will get back to you soon

Cheers

Joey

**Comment by samapriya** [comment]
Issue localized to a single machine, could not reproduce error at this end
