### ISSUE TITLE
Service account authorization for uploading

### ISSUE THREAD

**Issue by francbartoli** [samapriya/gee_asset_manager_addon#4]
Just a check if we can make it working from a json file with SA credentials and add support for that in your functions. Imagine we can do:

```python
>>> from google.oauth2 import service_account # here I used a service account but let's imagine we can get credentials with a normal user too
>>> from google.auth.transport.requests import AuthorizedSession
>>> authed_session = AuthorizedSession(service_account.Credentials.from_service_account_file('file.json'), scopes=scopes)

>>> resp_token = authed_session.get('https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=' + token)

>>> print resp_token.text
{
 "azp": "<client_id>",
 "aud": "<client_id>",
 "sub": "<client_id>",
 "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/plus.mehttps://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/fusiontables https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/earthengine",
 "exp": "1511349844",
 "expires_in": "653",
 "email": "<project_id>@<project_id>.iam.gserviceaccount.com",
 "email_verified": "true",
 "access_type": "offline"
} 
```

now having this valid oauth2 token can we use it for making authorized requests for upload to earthengine?

GEE team says it not possible but why not if the devstorage scope is there?

**Comment by samapriya** [comment]
That's an interesting idea and something I have not tried but let me know if you are able to proceed in that direction. something to revisit during next iterations.

**Comment by francbartoli** [comment]
Well at the moment after validating the token I'm receiving a redirect response to `https://www.google.com/accounts/ServiceLogin?service=ah&passive=true&continue=https://appengine.google.com/_ah/conflogin%3Fcontinue%3Dhttps://ee-api.appspot.com/assets/upload/geturl`

calling the `https://ee-api.appspot.com/assets/upload/geturl` endpoint which means the bearer token in the authorization header is not recognized.

**Comment by samapriya** [comment]
Thanks to work by Lucakz this has already been added as a feature, I just took time to update the issue :)
