### ISSUE TITLE
upload tiffs with bandnames

### ISSUE THREAD

**Issue by kongdd** [samapriya/gee_asset_manager_addon#5]
Can I upload tiff files with bandnames? 
[`earthengine` ](https://github.com/google/earthengine-api/blob/master/python/ee/cli/commands.py#L987)has the parameter of `--bands`. Can I put bandnames in metadata?

**Comment by samapriya** [comment]
Thanks to Lukasz for his original work on upload code, this was already done, I had not updated the upload code. The current update to v0.2.5 fixes that and allows you to pass, band names.
