### ISSUE TITLE
Incorrect credentials

### ISSUE THREAD

**Issue by edtrochim** [samapriya/gee_asset_manager_addon#6]
I am getting an error "2018-11-01 21:25:48,412 :: root :: ERROR :: Incorrect credentials. Probably. If you are sure the credentials are OK, refresh the authentication token. If it did not work report a problem. They might have changed something in the Matrix." while trying to upload images from a folder to a new image collection. The collection gets created, the first image starts getting processed and then that error comes up. 

I have checked that my two-step verification is off, that I've allowed less secure apps to have access and tried two different accounts. I've also tried multiple times on different days. Any further suggestions?

**Comment by samapriya** [comment]
This is a temporary issue when something changes at Google's backend and usually reverts back I could not reproduce it but if it happens again wait for couple of hours and if this is persistent reopen this issue
