### ISSUE TITLE
Search tool improvement

### ISSUE THREAD

**Issue by giswqs** [samapriya/gee_asset_manager_addon#9]
The search tool is fantastic! It would be nicer if you can add another column to indicate whether each returned asset id is an Image, ImageCollection, or FeatureCollection.

**Comment by samapriya** [comment]
Made all the improvements the output is now a JSON object, with earthengine asset type as a snippet to directly copy-paste into code and will also return start and end dates. Closing since requested improvements were made in v0.4.1

```
    {
        "index": 8,
        "title": "MCD45A1.051 Burned Area Monthly Global 500m",
        "ee_id_snippet": "ee.ImageCollection('MODIS/051/MCD45A1')",
        "start_date": "2000-04-01",
        "end_date": "2020-04-20"
    },
```
